# Generated by Django 5.0.14 on 2026-05-03 11:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Комиссия, %')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('color', models.CharField(default='#6366f1', max_length=32, verbose_name='Цвет (UI)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма до комиссии')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Комиссия')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='На руки')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='Затрачено времени, мин.')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'В работе'), ('completed', 'Завершён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('tags', models.CharField(blank=True, default='', max_length=512, verbose_name='Теги')),
                ('ai_feedback', models.TextField(blank=True, default='', verbose_name='Отзыв AI')),
                ('ai_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка AI')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.platform', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-completed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('first_order_date', models.DateField(blank=True, null=True, verbose_name='Дата первого заказа')),
                ('skills', models.TextField(blank=True, default='', verbose_name='Навыки')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс')),
                ('target_monthly_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Целевой месячный доход')),
                ('mistral_api_key_encrypted', models.CharField(blank=True, default='', max_length=512, verbose_name='Mistral API key (encrypted)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['start_date'],
            },
        ),
    ]
