# Generated by Django 5.0.14 on 2026-05-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Промпт')),
                ('response', models.TextField(blank=True, default='', verbose_name='Ответ')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('error', 'Ошибка'), ('timeout', 'Таймаут')], default='success', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Лог AI',
                'verbose_name_plural': 'Логи AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
