# Generated by Django 5.0.14 on 2026-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_ai_log_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_insights',
            field=models.TextField(blank=True, default='', verbose_name='AI-рекомендации'),
        ),
    ]
