# Generated by Django 5.0.14 on 2026-05-03 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_ai_insights_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Когда начали работу над заказом', null=True, verbose_name='Дата начала заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_spent_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Затраченное время в часах (можно рассчитать автоматически)', max_digits=5, null=True, verbose_name='Время (часы)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', editable=False, help_text='Автоматически генерируется AI при сохранении', verbose_name='Отзыв AI'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ai_rating',
            field=models.IntegerField(blank=True, editable=False, help_text='Автоматически генерируется AI при сохранении', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка AI'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Когда заказ был завершён', null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Устаревшее поле, используйте time_spent_hours', verbose_name='Затрачено времени, мин. (deprecated)'),
        ),
    ]
